/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.HomeAddressAttributes;
import model.HomeAddressAttributesView;

/**
 *
 * @author poorv
 */
public class CreateHAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateHAJPanel
     */
    HomeAddressAttributesView HAView;
    public CreateHAJPanel(HomeAddressAttributesView HAView) {
        initComponents();
        this.HAView = HAView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateHomeAddress = new javax.swing.JLabel();
        lblhfname = new javax.swing.JLabel();
        lblhlname = new javax.swing.JLabel();
        lblhpassport = new javax.swing.JLabel();
        lblHA1 = new javax.swing.JLabel();
        lblHA2 = new javax.swing.JLabel();
        txthfname = new javax.swing.JTextField();
        txthlname = new javax.swing.JTextField();
        txthpassport = new javax.swing.JTextField();
        txthHA1 = new javax.swing.JTextField();
        txthHA2 = new javax.swing.JTextField();
        btnHASave = new javax.swing.JButton();

        lblCreateHomeAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCreateHomeAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateHomeAddress.setText("Create Home Address");

        lblhfname.setText("HA First Name:");

        lblhlname.setText("HA Last Name:");

        lblhpassport.setText("HA Passport:");

        lblHA1.setText("HA House Address 1:");

        lblHA2.setText("HA House Address 2:");

        txthfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthfnameActionPerformed(evt);
            }
        });

        btnHASave.setText("HA Save");
        btnHASave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHASaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblhfname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblhlname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblhpassport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHA2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txthfname)
                    .addComponent(txthlname, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txthpassport, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txthHA1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txthHA2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(btnHASave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblCreateHomeAddress)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhfname)
                    .addComponent(txthfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhlname)
                    .addComponent(txthlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhpassport)
                    .addComponent(txthpassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHA1)
                    .addComponent(txthHA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHA2)
                    .addComponent(txthHA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnHASave)
                .addContainerGap(225, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txthfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthfnameActionPerformed

    private void btnHASaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHASaveActionPerformed
        // TODO add your handling code here:
    String hfname = txthfname.getText();
    String hlname = txthlname.getText();
    String hpassport = txthpassport.getText() ;
    String hHA1 = txthHA1.getText();
    String hHA2= txthHA2.getText();
    
    HomeAddressAttributes ha = HAView.addNewHA();
    
   ha.setHfname(hfname);
   ha.setHlname(hlname);
   ha.setHpassport(hpassport);
   ha.sethHA1(hHA1);
   ha.sethHA2(hHA2);
   
    JOptionPane.showMessageDialog(this, "new HA Added");
    
    txthfname.setText("");
    txthlname.setText("");
    txthpassport.setText("");
    txthHA1.setText("");
    txthHA2.setText("");
        
        
    }//GEN-LAST:event_btnHASaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHASave;
    private javax.swing.JLabel lblCreateHomeAddress;
    private javax.swing.JLabel lblHA1;
    private javax.swing.JLabel lblHA2;
    private javax.swing.JLabel lblhfname;
    private javax.swing.JLabel lblhlname;
    private javax.swing.JLabel lblhpassport;
    private javax.swing.JTextField txthHA1;
    private javax.swing.JTextField txthHA2;
    private javax.swing.JTextField txthfname;
    private javax.swing.JTextField txthlname;
    private javax.swing.JTextField txthpassport;
    // End of variables declaration//GEN-END:variables
}
