/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;


import javax.swing.JOptionPane;
import model.LocalAddressAttributes;
import model.LocalAddressAttributesView;

/**
 *
 * @author poorv
 */
public class CreateLAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateLAJPanel
     */
    LocalAddressAttributesView LAView;
    public CreateLAJPanel(LocalAddressAttributesView LAView) {
        initComponents();
        this.LAView= LAView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLAfname = new javax.swing.JTextField();
        txtLAlname = new javax.swing.JTextField();
        txtLApassport = new javax.swing.JTextField();
        txtLAadd1 = new javax.swing.JTextField();
        txtLAadd2 = new javax.swing.JTextField();
        lblCreateLocalAddress = new javax.swing.JLabel();
        btnLASave = new javax.swing.JButton();
        lblLAfname = new javax.swing.JLabel();
        lblLAlname = new javax.swing.JLabel();
        lblLApassport = new javax.swing.JLabel();
        lblLAadd1 = new javax.swing.JLabel();
        lblLAadd2 = new javax.swing.JLabel();

        txtLAfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLAfnameActionPerformed(evt);
            }
        });

        lblCreateLocalAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCreateLocalAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateLocalAddress.setText("Create Local Address");

        btnLASave.setText("LA Save");
        btnLASave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLASaveActionPerformed(evt);
            }
        });

        lblLAfname.setText("LA First Name:");

        lblLAlname.setText("LA Last Name:");

        lblLApassport.setText("LA Passport:");

        lblLAadd1.setText("LA House Address 1:");

        lblLAadd2.setText("LA House Address 2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateLocalAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLAfname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLAlname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLApassport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLAadd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLAadd2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLAfname)
                    .addComponent(txtLAlname, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtLApassport, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtLAadd1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtLAadd2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(btnLASave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblCreateLocalAddress)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLAfname)
                    .addComponent(txtLAfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLAlname)
                    .addComponent(txtLAlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLApassport)
                    .addComponent(txtLApassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLAadd1)
                    .addComponent(txtLAadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLAadd2)
                    .addComponent(txtLAadd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnLASave)
                .addContainerGap(225, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLAfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLAfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLAfnameActionPerformed

    private void btnLASaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLASaveActionPerformed
        // TODO add your handling code here:
        
    String LAfname = txtLAfname.getText();
    String LAlname = txtLAlname.getText();
    String LApassport = txtLApassport.getText();
    String LAadd1 = txtLAadd1.getText();
    String LAadd2 = txtLAadd2.getText();
    
    LocalAddressAttributes la = LAView.addNewLA();
    
    la.setLAfname(LAfname);
    la.setLAlname(LAlname);
    la.setLApassport(LApassport);
    la.setLAadd1(LAadd1);
    la.setLAadd2(LAadd2);
    
    JOptionPane.showMessageDialog(this, "New LA Added");
    
    txtLAfname.setText("");
    txtLAlname.setText("");
    txtLApassport.setText("");
    txtLAadd1.setText("");
    txtLAadd2.setText("");
    
    }//GEN-LAST:event_btnLASaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLASave;
    private javax.swing.JLabel lblCreateLocalAddress;
    private javax.swing.JLabel lblLAadd1;
    private javax.swing.JLabel lblLAadd2;
    private javax.swing.JLabel lblLAfname;
    private javax.swing.JLabel lblLAlname;
    private javax.swing.JLabel lblLApassport;
    private javax.swing.JTextField txtLAadd1;
    private javax.swing.JTextField txtLAadd2;
    private javax.swing.JTextField txtLAfname;
    private javax.swing.JTextField txtLAlname;
    private javax.swing.JTextField txtLApassport;
    // End of variables declaration//GEN-END:variables
}
