/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.BankAccountAttributes;
import model.BankAccountAttributesView;

/**
 *
 * @author poorv
 */
public class CreateBankAccountJpanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateBankAccountJpanel
     */
    BankAccountAttributesView BAView;
    public CreateBankAccountJpanel(BankAccountAttributesView BAView) {
        initComponents();
        this.BAView= BAView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtdebtAmt = new javax.swing.JTextField();
        lblCreateBankAccount = new javax.swing.JLabel();
        btnBASave = new javax.swing.JButton();
        lblBAfname = new javax.swing.JLabel();
        lblBAlname = new javax.swing.JLabel();
        lblBApassport = new javax.swing.JLabel();
        lblAccType = new javax.swing.JLabel();
        txtBAfname = new javax.swing.JTextField();
        lbldebtAmt = new javax.swing.JLabel();
        txtBAlname = new javax.swing.JTextField();
        txtBApassport = new javax.swing.JTextField();
        txtAccType = new javax.swing.JTextField();
        lblcreditAmt = new javax.swing.JLabel();
        txtCreditAmt = new javax.swing.JTextField();

        lblCreateBankAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCreateBankAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateBankAccount.setText("Create Bank Account");

        btnBASave.setText("BA Save");
        btnBASave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBASaveActionPerformed(evt);
            }
        });

        lblBAfname.setText("BA First Name:");

        lblBAlname.setText("BA Last Name:");

        lblBApassport.setText("BA Passport:");

        lblAccType.setText("Account Type:");

        txtBAfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBAfnameActionPerformed(evt);
            }
        });

        lbldebtAmt.setText("Debt Amt:");

        lblcreditAmt.setText("Credit Amt:");

        txtCreditAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditAmtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateBankAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBAfname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBAlname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBApassport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAccType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbldebtAmt, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(lblcreditAmt, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBAfname)
                    .addComponent(txtBAlname, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtBApassport, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtAccType, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtdebtAmt, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(btnBASave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCreditAmt))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblCreateBankAccount)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBAfname)
                    .addComponent(txtBAfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBAlname)
                    .addComponent(txtBAlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBApassport)
                    .addComponent(txtBApassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccType)
                    .addComponent(txtAccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldebtAmt)
                    .addComponent(txtdebtAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcreditAmt)
                    .addComponent(txtCreditAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnBASave)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBASaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBASaveActionPerformed
        // TODO add your handling code here:
        
    String BAfname = txtBAfname.getText();
    String BAlname = txtBAlname.getText();
    String BAPassport = txtBApassport.getText() ;
    String AccountType = txtAccType.getText();
    String debtAmt = txtdebtAmt.getText();
    String creditAmt = txtCreditAmt.getText();
    
    BankAccountAttributes ba = BAView.addNewBA();
    
    ba.setBAfname(BAfname);
    ba.setBAlname(BAlname);
    ba.setBAPassport(BAPassport);
    ba.setAccountType(AccountType);
    ba.setCreditAmt(creditAmt);
    ba.setDebtAmt(debtAmt);
    
    JOptionPane.showMessageDialog(this, "The bank account details added");
    
    txtBAfname.setText("");
    txtBAlname.setText("");
    txtBApassport.setText("");
    txtAccType.setText("");
    txtAccType.setText("");
    txtdebtAmt.setText("");
    txtCreditAmt.setText("");
    
    
    
    
    
    }//GEN-LAST:event_btnBASaveActionPerformed

    private void txtBAfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBAfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBAfnameActionPerformed

    private void txtCreditAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditAmtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBASave;
    private javax.swing.JLabel lblAccType;
    private javax.swing.JLabel lblBAfname;
    private javax.swing.JLabel lblBAlname;
    private javax.swing.JLabel lblBApassport;
    private javax.swing.JLabel lblCreateBankAccount;
    private javax.swing.JLabel lblcreditAmt;
    private javax.swing.JLabel lbldebtAmt;
    private javax.swing.JTextField txtAccType;
    private javax.swing.JTextField txtBAfname;
    private javax.swing.JTextField txtBAlname;
    private javax.swing.JTextField txtBApassport;
    private javax.swing.JTextField txtCreditAmt;
    private javax.swing.JTextField txtdebtAmt;
    // End of variables declaration//GEN-END:variables
}
