/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Business.Address;
import Business.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author poorv
 */
public class ViewPersonJPanel extends javax.swing.JPanel {
    private JPanel UserProcessContainer;
    private Person person;

    /**
     * Creates new form ViewPersonJPanel
     */
    

    ViewPersonJPanel(JPanel UserProcessContainer, Person person) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.person = person;
        populatePersonDetails();
        btnVSave.setEnabled(false);
        btnVUpdate.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblZipCode = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        lblZipCode1 = new javax.swing.JLabel();
        txtZipCode1 = new javax.swing.JTextField();
        lblVWorkAddress = new javax.swing.JLabel();
        lblVHomeAddress = new javax.swing.JLabel();
        lblVStreetAddress = new javax.swing.JLabel();
        txtVStreetAddress = new javax.swing.JTextField();
        lblVCity = new javax.swing.JLabel();
        txtVCity = new javax.swing.JTextField();
        lblVUnitNumber = new javax.swing.JLabel();
        txtVUnitNumber = new javax.swing.JTextField();
        lblVState1 = new javax.swing.JLabel();
        txtVState1 = new javax.swing.JTextField();
        lblVStreetAddress1 = new javax.swing.JLabel();
        txtVStreetAddress1 = new javax.swing.JTextField();
        btnVBack = new javax.swing.JButton();
        lblViewPerson = new javax.swing.JLabel();
        lblVCity1 = new javax.swing.JLabel();
        lblVFirstName = new javax.swing.JLabel();
        txtVCity1 = new javax.swing.JTextField();
        lblVSSN = new javax.swing.JLabel();
        lblVLastName = new javax.swing.JLabel();
        lblVLiscenceNumber = new javax.swing.JLabel();
        txtVState = new javax.swing.JTextField();
        txtVFirstName = new javax.swing.JTextField();
        txtVSSN = new javax.swing.JTextField();
        lblVState = new javax.swing.JLabel();
        lblVUnitNumber1 = new javax.swing.JLabel();
        txtVLastName = new javax.swing.JTextField();
        txtVUnitNumber1 = new javax.swing.JTextField();
        txtVliscenceNumber = new javax.swing.JTextField();
        btnVSave = new javax.swing.JButton();
        btnVUpdate = new javax.swing.JButton();
        lblVZipCode = new javax.swing.JLabel();
        txtVZipCode = new javax.swing.JTextField();
        lblVZipCode1 = new javax.swing.JLabel();
        txtVZipCode1 = new javax.swing.JTextField();

        lblZipCode.setText("Zip Code");

        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });

        lblZipCode1.setText("Zip Code");

        txtZipCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCode1ActionPerformed(evt);
            }
        });

        lblVWorkAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVWorkAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVWorkAddress.setText("Work Address");
        lblVWorkAddress.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblVHomeAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVHomeAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVHomeAddress.setText("Home Address");
        lblVHomeAddress.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblVStreetAddress.setText("Street Address");

        txtVStreetAddress.setEnabled(false);

        lblVCity.setText("City");

        txtVCity.setEnabled(false);

        lblVUnitNumber.setText("Unit Number");

        txtVUnitNumber.setEnabled(false);
        txtVUnitNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVUnitNumberActionPerformed(evt);
            }
        });

        lblVState1.setText("State");

        txtVState1.setEnabled(false);

        lblVStreetAddress1.setText("Street Address");

        txtVStreetAddress1.setEnabled(false);

        btnVBack.setText("Back");
        btnVBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVBackActionPerformed(evt);
            }
        });

        lblViewPerson.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblViewPerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewPerson.setText("View Person");
        lblViewPerson.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblVCity1.setText("City");

        lblVFirstName.setText("First Name");

        txtVCity1.setEnabled(false);

        lblVSSN.setText("Social Security Number");

        lblVLastName.setText("Last Name");

        lblVLiscenceNumber.setText("Liscence Number ");

        txtVState.setEnabled(false);

        txtVFirstName.setEnabled(false);

        txtVSSN.setEnabled(false);

        lblVState.setText("State");

        lblVUnitNumber1.setText("Unit Number");

        txtVLastName.setEnabled(false);

        txtVUnitNumber1.setEnabled(false);

        txtVliscenceNumber.setEnabled(false);

        btnVSave.setText("Save");
        btnVSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVSaveActionPerformed(evt);
            }
        });

        btnVUpdate.setText("Update");
        btnVUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVUpdateActionPerformed(evt);
            }
        });

        lblVZipCode.setText("Zip Code");

        txtVZipCode.setEnabled(false);
        txtVZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVZipCodeActionPerformed(evt);
            }
        });

        lblVZipCode1.setText("Zip Code");

        txtVZipCode1.setEnabled(false);
        txtVZipCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVZipCode1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(lblVFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtVSSN)
                    .addComponent(txtVFirstName))
                .addGap(266, 266, 266)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtVliscenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVLiscenceNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addGap(294, 294, 294))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblVLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblViewPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVStreetAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVStreetAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblVCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(283, 283, 283)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtVState1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblVState1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtVUnitNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblVUnitNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(42, 42, 42)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtVZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblVZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(txtVCity, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtVState, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblVCity, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblVState, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblVStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblVUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(txtVStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(270, 270, 270)
                                                .addComponent(txtVUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblVZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(btnVSave)
                                .addGap(159, 159, 159)
                                .addComponent(btnVUpdate)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblViewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVBack)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVFirstName)
                    .addComponent(lblVLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVSSN)
                    .addComponent(lblVLiscenceNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVliscenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblVWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVStreetAddress)
                    .addComponent(lblVUnitNumber)
                    .addComponent(lblVZipCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVCity)
                    .addComponent(lblVState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblVHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVStreetAddress1)
                    .addComponent(lblVUnitNumber1)
                    .addComponent(lblVZipCode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVStreetAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVUnitNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVCity1)
                    .addComponent(lblVState1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVState1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVSave)
                    .addComponent(btnVUpdate))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtVUnitNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVUnitNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVUnitNumberActionPerformed

    private void btnVBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVBackActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_btnVBackActionPerformed

    private void btnVUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVUpdateActionPerformed
        // TODO add your handling code here:
        txtVCity.setEnabled(true);
        txtVCity1.setEnabled(true);
        txtVFirstName.setEnabled(true);
        txtVLastName.setEnabled(true);
        txtVSSN.setEnabled(true);
        txtVState.setEnabled(true);
        txtVState1.setEnabled(true);
        txtVStreetAddress.setEnabled(true);
        txtVStreetAddress1.setEnabled(true);
        txtVUnitNumber.setEnabled(true);
        txtVUnitNumber1.setEnabled(true);
        txtVliscenceNumber.setEnabled(true);
        txtVZipCode.setEnabled(true);
        txtVZipCode1.setEnabled(true);
        btnVSave.setEnabled(true);
        btnVUpdate.setEnabled(false);
    }//GEN-LAST:event_btnVUpdateActionPerformed

    private void btnVSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVSaveActionPerformed
        // TODO add your handling code here:
        Address add1 = new Address();
        Address add2 = new Address();
        person.setFirstName(txtVFirstName.getText());
        person.setLastName(txtVLastName.getText());
        person.setLicenseNumber(txtVliscenceNumber.getText());
        person.setSSN(txtVSSN.getText());
        add1.setCity(txtVCity.getText());
        add1.setState(txtVState.getText());
        add1.setStreetAddress(txtVStreetAddress.getText());
        add1.setUnitNo(txtVUnitNumber.getText());
        add1.setZipCode(txtVZipCode.getText());
        person.setWorkAddress(add1);
        add2.setCity(txtVCity1.getText());
        add2.setState(txtVState1.getText());
        add2.setStreetAddress(txtVStreetAddress1.getText());
        add2.setUnitNo(txtVUnitNumber1.getText());
        add2.setZipCode(txtVZipCode1.getText());
        person.setHomeaddress(add2);
        btnVSave.setEnabled(false);
        btnVUpdate.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Person Updated Successfully");
    }//GEN-LAST:event_btnVSaveActionPerformed

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed

    private void txtZipCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCode1ActionPerformed

    private void txtVZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVZipCodeActionPerformed

    private void txtVZipCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVZipCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVZipCode1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVBack;
    private javax.swing.JButton btnVSave;
    private javax.swing.JButton btnVUpdate;
    private javax.swing.JLabel lblVCity;
    private javax.swing.JLabel lblVCity1;
    private javax.swing.JLabel lblVFirstName;
    private javax.swing.JLabel lblVHomeAddress;
    private javax.swing.JLabel lblVLastName;
    private javax.swing.JLabel lblVLiscenceNumber;
    private javax.swing.JLabel lblVSSN;
    private javax.swing.JLabel lblVState;
    private javax.swing.JLabel lblVState1;
    private javax.swing.JLabel lblVStreetAddress;
    private javax.swing.JLabel lblVStreetAddress1;
    private javax.swing.JLabel lblVUnitNumber;
    private javax.swing.JLabel lblVUnitNumber1;
    private javax.swing.JLabel lblVWorkAddress;
    private javax.swing.JLabel lblVZipCode;
    private javax.swing.JLabel lblVZipCode1;
    private javax.swing.JLabel lblViewPerson;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JLabel lblZipCode1;
    private javax.swing.JTextField txtVCity;
    private javax.swing.JTextField txtVCity1;
    private javax.swing.JTextField txtVFirstName;
    private javax.swing.JTextField txtVLastName;
    private javax.swing.JTextField txtVSSN;
    private javax.swing.JTextField txtVState;
    private javax.swing.JTextField txtVState1;
    private javax.swing.JTextField txtVStreetAddress;
    private javax.swing.JTextField txtVStreetAddress1;
    private javax.swing.JTextField txtVUnitNumber;
    private javax.swing.JTextField txtVUnitNumber1;
    private javax.swing.JTextField txtVZipCode;
    private javax.swing.JTextField txtVZipCode1;
    private javax.swing.JTextField txtVliscenceNumber;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JTextField txtZipCode1;
    // End of variables declaration//GEN-END:variables

    private void populatePersonDetails() {
        txtVFirstName.setText(person.getFirstName());
        txtVLastName.setText(person.getLastName());
        txtVSSN.setText(person.getSSN());
        txtVliscenceNumber.setText(person.getLicenseNumber());
        txtVCity.setText(person.getWorkAddress().getCity());
        txtVState.setText(person.getWorkAddress().getState());
        txtVCity1.setText(person.getHomeaddress().getCity());
        txtVState1.setText(person.getHomeaddress().getState());
        txtVStreetAddress.setText(person.getWorkAddress().getStreetAddress());
        txtVStreetAddress1.setText(person.getHomeaddress().getStreetAddress());
        txtVUnitNumber.setText(person.getWorkAddress().getUnitNo());
        txtVUnitNumber1.setText(person.getHomeaddress().getUnitNo());
        txtVZipCode.setText(person.getWorkAddress().getZipCode());
        txtVZipCode1.setText(person.getHomeaddress().getZipCode());
    }
}
