/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.CourseCatalog;
import Business.Business;
import Business.CourseCatalog.Course;
import Business.CourseCatalog.CourseCatalog;
import Business.CourseSchedule.CourseOffer;
import Business.CourseSchedule.CourseSchedule;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author saisr
 */
public class ScheduleSemesterJPanel extends javax.swing.JPanel {
    
     JPanel CardSequencePanel;
     Business business;

    /**
     * Creates new form ScheduleSemesterJPanel
     */
    public ScheduleSemesterJPanel(Business bz, JPanel jp) {
        CardSequencePanel=jp;
        this.business=bz;
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        drpDownBtn = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtBack = new javax.swing.JToggleButton();
        btnShowSemester = new javax.swing.JButton();
        txtShowCatalog = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtshowCatalog = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Schedule Semester ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Name", "Couse Number", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        drpDownBtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall2024", "Fall2025", "Fall2026", "Spring2025", "Spring2026" }));
        drpDownBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpDownBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Term :");

        txtBack.setText("<<Back");
        txtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBackActionPerformed(evt);
            }
        });

        btnShowSemester.setText("Show Semester Courses");
        btnShowSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSemesterActionPerformed(evt);
            }
        });

        txtShowCatalog.setText("Add Semester Schedule");
        txtShowCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShowCatalogActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");

        txtshowCatalog.setText("Show Course Catalog");
        txtshowCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtshowCatalogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(drpDownBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(btnShowSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(txtshowCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 203, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtShowCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(231, 231, 231)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(drpDownBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowSemester)
                    .addComponent(txtshowCatalog))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBack)
                    .addComponent(txtShowCatalog)
                    .addComponent(btnDelete))
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drpDownBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpDownBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpDownBtnActionPerformed

    private void txtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_txtBackActionPerformed

    private void txtshowCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtshowCatalogActionPerformed
        // TODO add your handling code here:
        refreshTable();
        
    }//GEN-LAST:event_txtshowCatalogActionPerformed

    private void btnShowSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSemesterActionPerformed
        // TODO add your handling code here:
        String selectedTerm = drpDownBtn.getSelectedItem().toString();
        
        CourseSchedule courseSchedule = business.getCourseSchedule(selectedTerm);
        SemestercoursesJPanel ssjp = new SemestercoursesJPanel(business, CardSequencePanel, courseSchedule);
        CardSequencePanel.add("Add Course", ssjp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnShowSemesterActionPerformed

    private void txtShowCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShowCatalogActionPerformed

        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
//        String cn =jTable1.
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        else{
        
        String  cn= jTable1.getValueAt(selectedRow,1).toString();
//        System.out.println(cn);
        Course cs = business.getCourseCatalog().getCourseByNumber(cn);
        System.out.println(cs.getCourseName());
        AddCoursetoScheduleJPanel ssjp = new AddCoursetoScheduleJPanel (business, CardSequencePanel,cs);
        CardSequencePanel.add("Add Course", ssjp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        }
        
    }//GEN-LAST:event_txtShowCatalogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnShowSemester;
    private javax.swing.JComboBox<String> drpDownBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton txtBack;
    private javax.swing.JButton txtShowCatalog;
    private javax.swing.JButton txtshowCatalog;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
         int rc = jTable1.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) jTable1.getModel()).removeRow(i);
        }



        CourseCatalog uad = business.getCourseCatalog();


        for (Course ua : uad.getCourseList()) {
            
            Object[] row = new Object[3];
           
            row[0] = ua.getCourseName(); //complete this..
            row[1] = ua.getCOurseNumber();
            
           row[2] = ua.getCredits();

            ((DefaultTableModel) jTable1.getModel()).addRow(row);
        }

        
    }
}

